// import type { Metadata } from "next";
// import "./globals.css";
// import ReduxProvider from "../app/componets/reduxprovider";
// import Header from "./componets/Header";
// import Footer from "./componets/Footer";


// export const metadata: Metadata = {
//   title: "Branded Leather",
//   description: "Generated by create next app",
//   other: {
//     "color-scheme": "light",
//   },
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className="bg-[#fdf7ee]" >
//         <ReduxProvider>
//         <Header/>
//         {children}
//         <Footer/>
//         </ReduxProvider>
//         </body>
//     </html>
//   );
// }



import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "../app/componets/reduxprovider";
import Header from "./componets/Header";
import Footer from "./componets/Footer";
import CartProvider from "./componets/CartProvider"; // 👈 import karo

export const metadata: Metadata = {
  title: "Branded Leather",
  description: "Generated by create next app",
  other: {
    "color-scheme": "light",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#fdf7ee]">
        <ReduxProvider>
          <CartProvider>   {/* 👈 Redux ke andar wrap karo */}
            <Header />
            {children}
            <Footer />
          </CartProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
