import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "../app/componets/reduxprovider";
import Header from "./componets/Header";
import Footer from "./componets/Footer";


export const metadata: Metadata = {
  title: "Branded Leather",
  description: "Generated by create next app",
  other: {
    "color-scheme": "light",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#FFFBF2]" >
        <ReduxProvider>
        <Header/>
        {children}
        <Footer/>
        </ReduxProvider>
        </body>
    </html>
  );
}
